dags:
  gitSync:
    enabled: true
    repo: https://github.com/mhmdsamir92/airflow-git-sync.git
    branch: master
    subPath: ""
    sshKeySecret: airflow-ssh-secret
extraSecrets:
  airflow-ssh-secret:
    data: |
      gitSshKey: 'PUT_YOUR_PRIVATE_KEY_HERE'